// Generated by https://quicktype.io

//Usuarios

export interface UsuarioResponse {
  usuario: Usuario;
  token?: string;
}

export interface Usuario {
  creado?: string;
  _id: string;
  nombre: string;
  apellido: string;
  correo: string;
  password?: string;
  __v?: number;
  foto?: string;
}

//Productos

export interface ProductosResponse {
  productos: Producto[];
}

export interface Producto {
  informacion?: string;
  creado: string;
  _id: string;
  nombre: string;
  year: string;
  precio: number;
  creador: string;
  existencia: number;
  foto: string;
  __v: number;
}

//Pedidos

export interface PedidosResponse {
  pedidos: Pedido[];
}

export interface Pedido {
  _id: string;
  estado: string;
  creado: string;
  cantidad: number;
  total: number;
  comprador: string;
  __v: number;
  producto: Producto[];
}
